services:
  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
    environment:
      REDIS_ENDPOINT: redis-14591.c270.us-east-1-3.ec2.redns.redis-cloud.com
      REDIS_PORT: "14591"
      REDIS_USER: default
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      - appnet
