services:
  app:
    build:
      context: ..
      dockerfile: ./Dockerfile
    image: microservice
    container_name: microservice
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - ../:/var/www
    depends_on:
      - mysql
      - redis
      - elasticsearch
    networks:
      - appnet
